import React from "react";
import Head from "next/head";
import Layout from "@/components/Layout";
import AnimatedText from "@/components/AnimatedText";
import Link from "next/link";
import { GithubIcon } from "@/components/Icons";
import Image from "next/image";
import microservice from "../../public/images/projects/microservices.png";
import ticket from "../../public/images/projects/ticket management.png";
import ecommerce from "../../public/images/projects/ecommerce.jpeg";
import bookstore from "../../public/images/projects/bookstore.jpeg";



const Project = ({ type, title, img, link, github }) => {
  return (
    <article className="w-full flex flex-col items-center relative justify-center rounded-2xl border border-solid border-dark bg-light p-6 relative">
      <div className="absolute top-0 -right-3 -z-10 w-[102%] h-[103%] rounded-2xl bg-dark" />

      <Link
        href={link}
        target="_blank"
        className="w-full cursor-pointer overflow-hidden rounded-lg"
      >
        <Image src={img} alt={title} className="w-full h-auto" />
      </Link>

      <div className="w-full flex flex-col items-start justify-between mt-4">
        <span className="text-primary font-medium text-xl">{type}</span>
        <Link
          href={link}
          target="_blank"
          className="hover:underline underline-offset"
        >
          <h2 className="my-2 w-full text-left text-4xl font-bold">{title}</h2>
        </Link>

        <div className="w-full my-2 flex items-center justify-between">
          <Link
            href={link}
            target="_blank"
            className="text-lg font-semibold underline"
          >
            Visit{" "}
          </Link>

          <Link href={github} target="_blank" className="w-8">
            {" "}
            <GithubIcon />{" "}
          </Link>
        </div>
      </div>
    </article>
  );
};

const FeaturedProject = ({ type, title, summary, img, link, github }) => {
  return (
    <article className="w-full flex items-center justify-between relative rounded-3xl border border-solid border-dark bg-light shadow-2xl p-12">
      <div className="absolute top-0 -right-3 -z-10 w-[102%] h-[103%] rounded-2xl bg-dark" />

      <Link
        href={link}
        target="_blank"
        className="w-1/2 cursor-pointer overflow-hidden rounded-lg"
      >
        <Image src={img} alt={title} className="w-full h-auto" />
      </Link>

      <div className="w-1/2 flex flex-col items-start justify-between pl-6">
        <span className="text-primary font-medium text-xl">{type}</span>
        <Link
          href={link}
          target="_blank"
          className="hover:underline underline-offset"
        >
          <h2 className="my-2 w-full text-left text-4xl font-bold">{title}</h2>
        </Link>
        <p className="my-2 font-medium text-dark">{summary}</p>

        <div className="mt-2 flex items-center">
          <Link href={github} target="_blank" className="w-10">
            {" "}
            <GithubIcon />{" "}
          </Link>
          <Link
            href={link}
            target="_blank"
            className="ml-4 rounded-lg bg-dark text-light p-2 px-6 text-lg font-semibold "
          >
            Visit Project
          </Link>
        </div>
      </div>
    </article>
  );
};

const projects = () => {
  return (
    <>
      <Head>
        <title>Gaurav | Projects </title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        <Layout>
          <AnimatedText
            text="Imagination Trumps Knowledge!"
            className="mb-16"
          />

          <div className="grid grid-cols-12 gap-24">
            <div className="col-span-12">
              <FeaturedProject
                title="Bottleneck Localizer"
                img={microservice}
                summary="A tool which is used to finding the bottleneck in the large
                scale microservice architecture using Machine Learning.Our tool ranks the based three parameters throughput, latency and error-rate."
                link="https://github.com/Gauravkumar2701/bottleneck-localization"
                github="https://github.com/Gauravkumar2701/bottleneck-localization"
                type="Research Work"
              />
            </div>

            <div className="col-span-6">
              <Project
                title="E-Commerce App"
                img={ecommerce}
                summary="Users have full control over ecommerce operations, including purchasing products, adding items to their cart, and registering as either admin or customer within the backend system."
                link="https://github.com/Gauravkumar2701/E-Commerce-App"
                github="https://github.com/Gauravkumar2701/E-Commerce-App"
                type="Bakend Project"
              />
            </div>

            <div className="col-span-6">
              <Project
                title="Ticket Management System"
                img={ticket}
                link="https://github.com/Gauravkumar2701/CRM-APPLICATION"
                github="https://github.com/Gauravkumar2701/CRM-APPLICATION"
                type="Bakend ProjectProject"
              />
            </div>

            <div className="col-span-12">
              <FeaturedProject
                title="Book Store"
                img={bookstore}
                summary="A robust application featuring CRUD operations (Create, Read, Update,
                    Delete) for book inventory.Supports both tabular and card views for user-friendly browsing. Revamped the UI using React and Vite, and fortified the backend with Express
                    for API development."
                link="https://bookstore-frontend-theta.vercel.app/"
                github="https://github.com/Gauravkumar2701/bookstore-frontend"
                type="Full Stack Project"
              />
            </div>

            {/* <div className="col-span-6">
              <Project
                title="sample"
                img={project1}
                summary="a cryposgraphty project "
                link="/"
                github="/"
                type="Featured Project"
              />
            </div>

            <div className="col-span-6">
              <Project
                title="sample"
                img={project1}
                summary="a cryposgraphty project "
                link="/"
                github="/"
                type="Featured Project" */}
              {/* /> */}
            {/* </div> */}
          </div>
        </Layout>
      </main>
    </>
  );
};

export default projects;
